name: tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy>=2.2.4
  - pandas>=2.2.3
  - scipy>=1.15.2
  - geopandas>=1.0.1
  - shapely>=2.1.0
  - plotly>=6.3.0
  - python-kaleido>=1.1.0